#from langchain.chat_models import ChatGoogleGemini
from langchain_google_genai import ChatGoogleGenerativeAI

from dotenv import load_dotenv
import os

load_dotenv()

#temperature controls the randomness of the output. Higher values (e.g., 1.0) make the output more random, while lower values (e.g., 0.2) make it more deterministic.
# temperature=0.7 is a common default that provides a good balance between creativity and coherence.
#temperature is a parameter that controls the randomness of the output generated by a language model. Higher values (e.g., 1.0) make the output more random and creative, while lower values (e.g., 0.2) make it more deterministic and focused. A common default value is 0.7, which provides a good balance between creativity and coherence.
#use case for temperature: If you want the model to generate more creative and diverse responses, you might set a higher temperature (e.g., 1.0). If you want more focused and deterministic responses, you might set a lower temperature (e.g., 0.2).

#max_completions_tokens limits the maximum number of tokens in the generated response. Setting it to None allows for unlimited tokens, but you can specify a limit (e.g., 100) to control the length of the output.


model = ChatGoogleGenerativeAI(
    model="gemini-3.1-flash-lite",
    temperature=1.0,  # Gemini 3.0+ defaults to 1.0
    max_tokens=None,
    timeout=None,
    max_retries=2,
    # other params...
)

result= model.invoke("What is the capital of France?")
print(result)

print(result.content)
